(define (equal? a b)
  (cond ((and (number? a) (number? b))
         (= a b))
        ((and (symbol? a) (symbol? b))
         (eq? a b))
        ((and (null? a) (null? b)) true)
        ((and (pair? a) (pair? b))
         (and (equal? (car a) (car b))
              (equal? (cdr a) (cdr b))))
        (else false)))
