(define (union-set set1 set2)
  (let ((list1 (tree->list-2 set1))
        (list2 (tree->list-2 set2)))
    (let ((merged (union-set-list list1 list2)))
      (list->tree merged))))

(define (intersection-set set1 set2)
  (let ((list1 (tree->list-2 set1))
        (list2 (tree->list-2 set2)))
    (let ((merged (intersection-set list1 list2)))
      (list->tree merged))))
